spring:
  profiles: default
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
---
spring:
  profiles: eureka-1
  application:
    name: service-discovery
eureka:
  client:
    serviceUrl:
      defaultZone: http://service-discovery-2:8761/eureka
server:
   port: 8761
---
spring:
  profiles: eureka-2
  application:
      name: service-discovery
  client:
    serviceUrl:
      defaultZone: http://service-discovery-1:8761/eureka
server:
   port: 8761
---
spring:
  profiles: eureka-3
  application:
      name: service-discovery
eureka:
  client:
    serviceUrl:
      defaultZone: http://service-discovery-1:8761/eureka
server:
   port: 8761