---
eureka:
     client:
       serviceUrl:
         defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: microservice-user
  profiles: default
server:
  port: 8080
---
eureka:
     client:
       serviceUrl:
         defaultZone: http://service-discovery-1:8761/eureka/
spring:
  application:
    name: microservice-user
  profiles: test
server:
  port: 80